# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: 'Release'
  project: 'PruebaMAUI/Mapa/Mapa.csproj' 

stages:
  - stage: Compilacion_Android
    displayName: 'Compilacion proyecto Android'
    jobs:
      - job: ValidationJob
        displayName: Validación Android
        pool: server    
        timeoutInMinutes: 4320 # job times out in 3 days
        steps: 
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
              notifyUsers: |
                  marlo15.9909@outlook.com
                  marianazacariaschavez@hotmail.com
              instructions: 'Validar el trabajo y realizar el resumen del mismo'
              onTimeout: 'resume'
        #- task: AndroidSigning@2
         # inputs:
         #   apkFiles: '**/*.apk'
         #   jarsign: true
         #   jarsignerKeystoreFile: 'pathToYourKeystoreFile'
         #   jarsignerKeystorePassword: '$(jarsignerKeystorePassword)'
         #   jarsignerKeystoreAlias: 'yourKeystoreAlias'
         #   jarsignerKeyPassword: '$(jarsignerKeyPassword)'
         #   zipalign: true
        #- task: CopyFiles@2
         # inputs:
          #  contents: '**/*.apk'
          #  targetFolder: '$(build.artifactStagingDirectory)'
        #- task: PublishBuildArtifacts@1
      
      - job: Job_CI_Android
        displayName: 'Compilacion Android'
        continueOnError: false
        dependsOn: ValidationJob